// front/interface/src/ClusterApp/components/ClusterElement.svelte
<script lang="ts">
    import type { TClusterImageInfo, TClusterInfo } from "../types";
    import { getEditorState } from "../state.svelte";
    import IconBtn from "../../shared/components/IconBtn.svelte";
    import Icon from "@iconify/svelte";
    import ClusterCSVExporter from "./ClusterCSVExporter.svelte";
    import ImageList from "./ImageList.svelte";
    import { getNameProvider } from "../../shared/naming.svelte";

    interface Props {
        cluster: TClusterInfo;
        expanded?: boolean;
        editing?: boolean;
        editable?: boolean;
        dti_transformed?: boolean;
        thumbnail?: boolean;
        selected?: boolean;
    }
    let {
        cluster,
        expanded = false,
        editing = $bindable(false),
        editable = false,
        dti_transformed = $bindable(false),
        thumbnail = false,
        selected = false,
    }: Props = $props();

    let renaming = $state(false);
    let elRef = $state<HTMLDivElement>();
    let nameInput = $state<HTMLInputElement>();
    let editor_state = getEditorState();
    let name_provider = getNameProvider();

    const N_SHOWN = { grid: 8, rows: 18 };
    let n_shown = $derived(N_SHOWN[editor_state.viewer_display]);

    let images:TClusterImageInfo[] = $state([]);

    // CALLBACKS
    function onRenameSubmit(e: Event) {
        e.preventDefault();
        const val = nameInput?.value;
        if (val) {
            cluster.name = val;
        }
        renaming = false;
    }

    function askForMerge() {
        editor_state.ask_cluster("cluster_merge", cluster.id);
    }

    const scrollIntoView = () => {
        setTimeout(() => elRef?.scrollIntoView({ behavior: "smooth", block: "center" }), 100);
    };

    $effect(() => {
        if (editing) {
            scrollIntoView();
        }
    });
    $effect(() => {
        cluster.images.length;
        images = name_provider.sortImages(cluster.images);
    });
</script>

<div
    class="cl-cluster box"
    class:cl-expanded={expanded || editing}
    class:cl-selected={selected || editing}
>
    <div class="cl-anchor" bind:this={elRef}></div>
    <div class="cl-props">
        <div class="cl-propcontent">
            {#if thumbnail}
                <h3>{cluster.name}</h3>
                <p>
                    {#if cluster.id >= 0}
                        Cluster #{cluster.id}, {cluster.images.length} images
                    {/if}
                </p>
            {:else}
                <div class="cl-propinfo">
                    <div class="cl-cluster-title">
                        {#if renaming && editing}
                            <form onsubmit={onRenameSubmit}>
                                <input
                                    type="text"
                                    bind:this={nameInput}
                                    defaultValue={cluster.name}
                                    autofocus
                                />
                                <a href="javascript:void(0)" onclick={onRenameSubmit} class="btn"
                                    ><Icon icon="mdi:check-bold" /></a
                                >
                            </form>
                        {:else}
                            <span>{cluster.name}</span>
                            {#if editing}
                                <a
                                    href="javascript:void(0)"
                                    class="btn is-edit"
                                    onclick={() => {
                                        renaming = true;
                                    }}
                                    title="Rename"><Icon icon="mdi:edit" /></a
                                >
                            {/if}
                        {/if}
                    </div>
                    <p>
                        {cluster.id >= 0 &&
                            `Cluster #${cluster.id}, ${cluster.images.length} images`}
                    </p>

                    {#if editable}
                        <p>
                            {#if editing}
                                <IconBtn
                                    icon="mdi:merge"
                                    label="Merge cluster with..."
                                    onclick={askForMerge}
                                />
                                <IconBtn
                                    icon="mdi:check-bold"
                                    label="End edition"
                                    onclick={() => (editing = false)}
                                />
                            {:else}
                                <IconBtn
                                    icon="mdi:edit"
                                    label="Edit cluster"
                                    onclick={() => (editing = true)}
                                />
                            {/if}
                        </p>
                    {:else}
                        <p>
                            <ClusterCSVExporter clusters={[cluster]} />
                            <!-- {btnExpand} TODO -->
                        </p>
                    {/if}
                </div>
            {/if}<!-- thumbnail -->

            {#if !thumbnail && cluster.proto_url}
                <div class="cl-protoinfo">
                    <p>
                        {#if dti_transformed}
                            <IconBtn
                                icon="mdi:image"
                                class="is-outline"
                                label="Show images"
                                onclick={() => {
                                    dti_transformed = false;
                                }}
                            />
                        {:else}
                            <IconBtn
                                icon="mdi:panorama-variant"
                                class="is-outline"
                                label="Show protos"
                                onclick={() => {
                                    dti_transformed = true;
                                }}
                            />
                        {/if}
                    </p>
                    <div class="cl-proto">
                        <img
                            src={(editor_state.base_url || "") + cluster.proto_url}
                            alt="cl-proto"
                            class="prototype"
                        />
                        {#if cluster.mask_url}
                            <img
                                src={(editor_state.base_url || "") + cluster.mask_url}
                                alt="mask"
                                class="mask"
                            />
                        {/if}
                    </div>
                </div>
            {/if}
        </div>

        {#if editable && !editing}
            <a
                class="cl-overlay cl-hoveroptions"
                href="javascript:void(0)"
                onclick={() => (editing = true)}
            >
                <IconBtn icon="mdi:edit" label="Edit cluster" />
                <IconBtn
                    icon="mdi:merge"
                    label="Merge with..."
                    onclick={(e) => {
                        e.stopPropagation();
                        askForMerge();
                    }}
                />
            </a>
        {/if}
    </div>
    <div class="cl-samples">
        <ImageList
            selectable={editing}
            {images}
            {dti_transformed}
            limit={expanded && !editing ? undefined : n_shown}
            onexpand={() => scrollIntoView()}
            disable_all={thumbnail}
            bind:expanded
        />
    </div>
</div>

// front/webpack/src/ClusterApp/components/ClusterElement.tsx
import React, { useEffect, useState } from "react";
import { ClusterEditorContext } from "../actions";
import { Icon } from "@iconify/react";
import { ClusterInfo, ClusterProps } from "../types";
import { BasicImageList, SelectableImageList } from "./ImageLists";
import { IconBtn } from "../../shared/IconBtn";
import { ClusterCSVExporter } from "./ClusterExporter";
import { NameProviderContext, sortImages } from "../../shared/naming";

const N_SHOWN = {"grid": 8, "rows": 18};

/*
  This file contains the React components that displays a cluster.

  Two versions are available:
  - ClusterElement: the full cluster, with all images, and the possibility to edit it
  - MiniClusterElement: a lightweight version of the cluster, with only a few images (for modale)
*/

// Lightweight cluster element for the cluster list in modale
export function MiniClusterElement(props: { info: ClusterInfo; selected: boolean; onClick?: () => void; limit?: number }) {
  const editorContext = React.useContext(ClusterEditorContext);
  const cluster = props.info;

  return (
    <div className={"cl-cluster box" + (props.selected ? " cl-selected" : "")} onClick={props.onClick}>
      <div className="cl-props">
        <div className="cl-propcontent">
          <h3>{cluster.name}</h3>
          <p>{cluster.id >= 0 && <React.Fragment>Cluster #{cluster.id}, {cluster.images.length} images</React.Fragment>} </p>
        </div>
      </div>
      <div className="cl-samples">
        <BasicImageList images={cluster.images} transformed={false} limit={props.limit || 5} />
      </div>
      {/* <a className="cl-overlay" href="javascript:void(0)"></a> */}
    </div>
  );
}


export function ClusterElement(props: ClusterProps) {
  const [expanded, setExpanded] = useState(false);
  const [transformed, setTransformed] = useState(false);
  const [renaming, setRenaming] = useState(false);
  const nameInput = React.createRef<HTMLInputElement>();
  const editorContext = React.useContext(ClusterEditorContext);
  const elRef = React.useRef<HTMLDivElement>(null);
  const nameContext = React.useContext(NameProviderContext);

  const cluster = props.info;
  const editable = editorContext?.state.editing;
  const n_shown = N_SHOWN[editorContext!.state.viewer_display];

  // useful functions
  const scrollIntoView = () => {
    setTimeout(() => elRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 100);
  }

  const onRenameSubmit = (e: React.SyntheticEvent) => {
    e.preventDefault();
    const val = nameInput.current!.value;
    if (val) {
      editorContext?.dispatch({ type: "cluster_rename", cluster_id: cluster.id, name: val});
    }
    setRenaming(false);
  };

  const toggleEdition = (val?: boolean) => {
    editorContext?.dispatch({ type: "viewer_focus", cluster_id: val ? cluster.id : null});
    if (!val) scrollIntoView();
    setRenaming(false);
  };

  const askForMerge = () => {
    editorContext?.dispatch({ type: "cluster_ask", cluster_id: cluster.id, for_action: "cluster_merge"})
  };

  // when expanded or edited, scroll to the element
  useEffect(() => {
    if (expanded || props.editing) scrollIntoView();
  }, [expanded, props.editing]);

  // sub components
  const btnMore = (cluster.images.length > n_shown &&
    <a className="cl-more card cl-placeholder" href="javascript:void(0)" onClick={() => {setExpanded(!expanded); scrollIntoView();}}>
      {expanded ? "–" : "+"}{cluster.images.length - n_shown}
    </a>
  );

  const btnExpand = (cluster.images.length > n_shown &&
    (expanded ?
      <p><IconBtn icon="mdi:chevron-up" label="Collapse" onClick={() => {setExpanded(false); scrollIntoView();}} /></p> :
      <p><IconBtn icon="mdi:chevron-down" label="Expand" onClick={() => {setExpanded(true)}} /></p>)
  );

  // render
  return (
    <div className={"cl-cluster box" + (expanded || props.editing ? " cl-expanded" : "")}>
      <div className="cl-anchor" ref={elRef}></div>
      <div className="cl-props">
        <div className="cl-propcontent">
          <div className="cl-propinfo">
            <div className="cl-cluster-title">
            {(renaming && props.editing) ?
                (<form onSubmit={onRenameSubmit}>
                  <input type="text" ref={nameInput} defaultValue={cluster.name} autoFocus></input>
                  <a href="javascript:void(0)" onClick={onRenameSubmit} className="btn"><Icon icon="mdi:check-bold" /></a>
                </form>) :
                (<React.Fragment>
                  <span>{cluster.name}</span>
                  {props.editing && <a href="javascript:void(0)" className="btn is-edit" onClick={() => {toggleEdition(true); setRenaming(true)}} title="Rename"><Icon icon="mdi:edit" /></a>}
                </React.Fragment>)
            }
            </div>

            <p>{cluster.id >= 0 && <React.Fragment>Cluster #{cluster.id}, {cluster.images.length} images</React.Fragment>}</p>


            {editable ?
            <p>
              {props.editing ?
              <React.Fragment>
                <IconBtn icon="mdi:merge" label="Merge cluster with..." onClick={askForMerge}/>
                <IconBtn icon="mdi:check-bold" label="End edition" onClick={() => toggleEdition(false)} />
              </React.Fragment>:
                <IconBtn icon="mdi:edit" label="Edit cluster" onClick={() => toggleEdition(true)} />}
            </p> :
              <p>
                <ClusterCSVExporter clusters={[cluster]} />
                {btnExpand}
              </p>}
          </div>
          {cluster.proto_url &&
          <div className="cl-protoinfo">
          <p>{transformed ?
              <IconBtn icon="mdi:image" className="is-outline" label="Show images" onClick={() => {setTransformed(false)}} /> :
              <IconBtn icon="mdi:panorama-variant" className="is-outline" label="Show protos" onClick={() => {setTransformed(true)}} />}
          </p>
            <div className="cl-proto">
              <img src={(editorContext?.state.base_url || "") + cluster.proto_url} alt="cl-proto" className="prototype" />
              {cluster.mask_url && false && <img src={(editorContext!.state.base_url || "") + cluster.mask_url} alt="mask" className="mask" />}
            </div>
          </div>}

        </div>

        {editable && !props.editing &&
        <a className="cl-overlay cl-hoveroptions" href="javascript:void(0)" onClick={() => toggleEdition(true)}>
          <IconBtn icon="mdi:edit" label="Edit cluster" />
          <IconBtn icon="mdi:merge" label="Merge with..." onClick={(e) => {e.stopPropagation(); askForMerge()}}/>
          </a>}
      </div>
      <div className="cl-samples">
          {props.editing ?
          <SelectableImageList images={sortImages(nameContext, cluster.images)} transformed={transformed} /> :
          <BasicImageList images={sortImages(nameContext, cluster.images)} transformed={transformed} limit={expanded ? undefined : n_shown} expander={btnMore}/>
          }
      </div>
    </div>
  );
}
