// front/interface/src/SimilarityApp/components/MatchRow.svelte
<script lang="ts">
    import { untrack } from "svelte";
    import ImageFileDisplay from "../../shared/components/ImageFileDisplay.svelte";
    import ImageInfos from "../../shared/components/ImageInfos.svelte";
    import type { TSimilarityMatches } from "../types";
    import MatchCSVExporter from "./MatchCSVExporter.svelte";
    import MatchGroup from "./MatchGroup.svelte";

    interface Props {
        matches: TSimilarityMatches;
        group_by_source: boolean;
        highlit?: boolean;
        threshold?: number;
    }
    let { matches, group_by_source, highlit, threshold }: Props = $props();
    let groups = $derived(
        group_by_source ? matches.matches_by_document : matches.matches.map((m) => [m])
    );
    let showAll = $state(false);
    let scrollRef = $state<HTMLElement | null>(null);

    function scrollToHighlit() {
        if (scrollRef) {
            scrollRef.scrollIntoView({ behavior: "smooth", block: "center" });
        }
    }

    $effect(() => {
        if (highlit) {
            untrack(scrollToHighlit);
        }
    });
</script>

<div class="match-row columns" class:highlit={highlit} bind:this={scrollRef}>
    <div class="column match-query">
        <ImageInfos image={matches.query} />
        <div class="columns is-multiline match-items is-centered">
            <ImageFileDisplay image={matches.query} disable_pin />
        </div>
        {#if groups.length > 5}
            <p>
                <a href="javascript:void(0)" onclick={() => (showAll = !showAll)}>
                    {showAll ? "Show only 5 best" : `Show all results`}
                </a>
            </p>
        {/if}
        <MatchCSVExporter matches={matches} threshold={threshold} />
    </div>
    <div class="column columns match-results">
        {#each groups.slice(0, showAll ? groups.length : 5) as grouped_by_source}
            <MatchGroup
                matches={grouped_by_source}
                grouped={group_by_source}
                {threshold}
                wref={matches.query}
            />
        {/each}
    </div>
</div>

// front/webpack/src/SimilarityApp/components/MatchRow.tsx
import React, { useEffect } from "react";
import { SimilarityMatches } from "../types";
import { ImageFileDisplay } from "../../shared/ImageFileDisplay";
import { MatchGroup } from "./MatchGroup";
import { MatchCSVExporter } from "./MatchExporter";
import { getImageName, getSourceName, NameProviderContext } from "../../shared/naming";
import { SimilarityHrefContext } from "./ImageSimBrowser";
import {ImageIdentification} from "../../shared/ImageIdentification";

interface MatchRowProps {
    matches: SimilarityMatches;
    group_by_source: boolean;
    highlit?: boolean;
    threshold?: number;
}

export function MatchRow({matches, group_by_source, highlit, threshold}: MatchRowProps) {
    /*
    Component to render a single watermark match.
    */
    const [showAll, toggleShowAll] = React.useReducer((showAll) => !showAll, false);
    const groups = group_by_source ? matches.matches_by_document : matches.matches.map(m => [m]);
    const scrollRef = React.useRef<HTMLDivElement>(null);
    const nameProvider = React.useContext(NameProviderContext);
    const matchesRef = React.useContext(SimilarityHrefContext).matchesHref || (() => undefined);

    useEffect(() => {
        if (highlit) {
            scrollRef.current?.scrollIntoView({behavior: "smooth", block: "center"});
        }
    }, [highlit]);

    return (
        <div className={"match-row columns " + (highlit?"highlit":"")} ref={scrollRef}>
            <div className="column match-query">
                <ImageIdentification image={matches.query}/>
                <div className="columns is-multiline match-items is-centered">
                    <ImageFileDisplay image={matches.query} href={matchesRef(matches.query)}/>
                </div>
                {groups.length > 5 && <p>
                    <a href="javascript:void(0)" onClick={toggleShowAll}>
                        {showAll ? "Show only 5 best" : `Show all results`}
                    </a>
                </p>}
                <MatchCSVExporter matches={matches} threshold={threshold}/>
            </div>
            <div className="column columns match-results">
                {groups.slice(0, showAll ? groups.length : 5).map((grouped_by_source, k) => (
                    <MatchGroup key={k} matches={grouped_by_source} grouped={group_by_source} threshold={threshold} wref={matches.query} />
                ))}
            </div>
        </div>
    );
}
