// front/interface/src/SimilarityApp/components/MatchGroup.svelte
<script lang="ts">
    import Icon from "@iconify/svelte";
    import ImageInfos from "../../shared/components/ImageInfos.svelte";
    import type { TSimilarityMatch } from "../types";
    import IconBtn from "../../shared/components/IconBtn.svelte";
    import ImageFileDisplay from "../../shared/components/ImageFileDisplay.svelte";
    import type { TImageInfo } from "../../shared/types";
    import { matchesHRef } from "./SimBrowser.svelte";

    interface Props {
        matches: TSimilarityMatch[];
        grouped?: boolean;
        threshold?: number;
        wref?: TImageInfo;
    }
    
    const { matches, grouped, threshold, wref }: Props = $props();
    
    let expanded = $state(false);
</script>

{#if !threshold || matches[0].similarity >= threshold}
<div class="match-group">
    <div class={expanded ? "match-expanded" : "match-excerpt"}>
        <p>
            {#if grouped}
                <Icon icon="mdi:folder"></Icon>
                {matches[0].image.document?.name || matches[0].image.document?.uid}
            {:else}
                <ImageInfos image={matches[0].image} />
            {/if}
        </p>
        <div class="columns is-multiline match-items">
            {#each matches as match, idx (match.image.id)}
                {#if (expanded || idx == 0) && (!threshold || match.similarity >= threshold)}
                    <ImageFileDisplay comparison={wref} href={matchesHRef(match.image)} {...match} disable_pin />
                {/if}
            {/each}
        </div>
        {#if matches.length > 1}
            <IconBtn
                icon={expanded ? "mdi:close" : "mdi:animation-plus"}
                onclick={() => (expanded = !expanded)}
                label={expanded ? "Collapse" : `+${matches.length - 1}`}
            />
        {/if}
    </div>
</div>
{/if}

// front/webpack/src/SimilarityApp/components/MatchGroup.tsx
import React, { useReducer } from "react";
import { SimilarityMatch } from "../types";
import { ImageInfo } from "../../shared/types";
import { ImageFileDisplay } from "../../shared";
import { Icon } from "@iconify/react";
import { IconBtn } from "../../shared";
import { NameProviderContext, getImageName, getSourceName } from "../../shared/naming";
import { SimilarityHrefContext } from "./ImageSimBrowser";
import {ImageIdentification} from "../../shared";

interface MatchGroupProps {
    matches: SimilarityMatch[];
    grouped?: boolean;
    threshold?: number;
    wref?: ImageInfo;
}

export function MatchGroup({ matches, grouped, threshold, wref }: MatchGroupProps) {
    /*
    Component to render a group of watermark matches.
    */
    // expand the group or not
    const [expanded, toggleExpand] = useReducer((expanded) => !expanded, false);
    const nameProvider = React.useContext(NameProviderContext);
    const matchesRef = React.useContext(SimilarityHrefContext).matchesHref || (() => undefined);

    return (
        (!threshold || matches[0].similarity >= threshold) &&
        <div className="column match-group">
            <div className={expanded ? "match-expanded" : "match-excerpt"}>
                <p>{grouped ?
                    <React.Fragment>
                        <Icon icon="mdi:folder"></Icon>
                        {getSourceName(nameProvider, matches[0].image.document)}
                    </React.Fragment> :
                    <ImageIdentification image={matches[0].image}/>
                    }</p>
                <div className="columns is-multiline match-items">
                    {matches.map((match, idx) => (
                        (expanded || idx==0) && (!threshold || match.similarity >= threshold) && <ImageFileDisplay key={idx} comparison={wref} href={matchesRef(match.image)} {...match} />
                    ))}
                </div>
                {matches.length > 1 && <IconBtn icon={expanded ? "mdi:close" : "mdi:animation-plus"} onClick={toggleExpand} label={expanded ? "Collapse" : `+${matches.length -1}`}/>}
            </div>
        </div>
    );
}
