// front/webpack/src/SimilarityApp/components/SimilarityApp.tsx
import React from "react";
import { SimilarityIndex, SimilarityMatches } from "../types";
import { NameProvider } from "../../shared/types";
import { ImageMagnifier, MagnifyingContext, MagnifyProps } from "../../shared/ImageMagnifier";
import { fetchIIIFNames, NameProviderContext } from "../../shared/naming";
import { IconBtn } from "../../shared/IconBtn";
import { ImageSimBrowser } from "./ImageSimBrowser";
import { ClusteringTool } from "./ClusteringTool";
import { ImageTooltip, TooltipContext, TooltipProps } from "../../shared/ImageTooltip";

export interface SimilarityProps {
    index: SimilarityIndex;
    matches: SimilarityMatches[];
    mode?: SimilarityMode;
}

export type SimilarityMode = "cluster" | "browse";

export function SimilarityApp(props: SimilarityProps) {

    const [nameProvider, setContext] = React.useState<NameProvider>({});
    const [magnifying, setMagnifying] = React.useState<MagnifyProps | null>(null);
    const [mode, setMode] = React.useState<SimilarityMode>(props.mode || "cluster");
    const [tooltip, setTooltip] = React.useState<TooltipProps | undefined>(undefined);

    React.useEffect(() => {
        fetchIIIFNames(props.index.sources, (ncontext: NameProvider) => setContext({ ...nameProvider, ...ncontext }));
    }, []);

    const addtitional_toolbar = (
        <div className="toolbar-item toolbar-btn">
            {mode != "browse" && <IconBtn icon="mdi:folder" onClick={() => setMode("browse")} label="Switch to Browse Mode" />}
            {mode != "cluster" && <IconBtn icon="mdi:graph" onClick={() => setMode("cluster")} label="Cluster the results" />}
        </div>
    )


    return (
        <NameProviderContext.Provider value={nameProvider}>
            <TooltipContext.Provider value={{ setTooltip }}>
                <MagnifyingContext.Provider value={{ magnify: setMagnifying }}>
                    {mode === "browse" && <ImageSimBrowser index={props.index} matches={props.matches} extra_toolbar_items={addtitional_toolbar} />}
                    <ClusteringTool index={props.index} matches={props.matches} visible={mode == "cluster"} extra_toolbar_items={addtitional_toolbar} />
                    {magnifying && <ImageMagnifier {...magnifying} />}
                    {tooltip && <ImageTooltip {...tooltip} />}
                </MagnifyingContext.Provider>
            </TooltipContext.Provider>
        </NameProviderContext.Provider>
    )

}

// front/interface/src/SimilarityApp/components/SimilarityApp.svelte
<script lang="ts">
    import IconBtn from "../../shared/components/IconBtn.svelte";
    import ImageMagnifier, { setMagnifyingContext } from "../../shared/components/ImageMagnifier.svelte";
    import NameProvider, { setNameProvider } from "../../shared/naming.svelte";
    import { unserializeSimilarityMatrix } from "../converters";
    import type { TSimilarityIndex, TSimilarityMatches } from "../types";
    import ClusteringTool from "./ClusteringTool.svelte";
    import SimBrowser from "./SimBrowser.svelte";

    interface Props {
        source_index_url: string;
        sim_matrix_url: string;
        mode?: "cluster" | "browse";
    }
    let { source_index_url, sim_matrix_url, mode }: Props = $props();

    let index:TSimilarityIndex = $state({sources: [], images: [], transpositions: []});
    let matches:TSimilarityMatches[] = $state([]);
    let loading = $state(true);

    let magnifying = $state({});
    setMagnifyingContext(magnifying);

    let name_provider = new NameProvider();
    setNameProvider(name_provider);
    
    $effect(() => {
        Promise.all([
            fetch(source_index_url).then(response => response.json()),
            fetch(sim_matrix_url).then(response => response.json())
        ]).then(([raw_index, raw_matches]) => {
            const data = unserializeSimilarityMatrix(raw_matches, raw_index);
            [ index, matches ] = [data.index, data.matches];
            name_provider.fetchIIIFNames(index.sources);
            loading = false;
        });
    });
</script>

{#if loading}
    <p>Loading...</p>
{:else}
    <ClusteringTool index={index!} matches={matches!} visible={mode == "cluster"}>
        {#snippet extra_toolbar_items()}
        <div class="toolbar-item toolbar-btn">
            <IconBtn icon="mdi:folder" onclick={() => mode = "browse"} label="Switch to Browse Mode" />
        </div>
        {/snippet}
    </ClusteringTool>
    {#if mode == "browse"}
        <SimBrowser index={index!} matches={matches!}>
            {#snippet extra_toolbar_items()}
            <div class="toolbar-item toolbar-btn">
                <IconBtn icon="mdi:graph" onclick={() => mode = "cluster"} label="Cluster the results" />
            </div>
            {/snippet}
        </SimBrowser>
    {/if}
{/if}

<ImageMagnifier {...magnifying} />
