// front/webpack/src/shared/ImageGeneric.tsx
/**
 * a generic display for an Image and its metadata.
 * inspired by SimilarityApp.components.MatchGroup
 *
 * ImageFileDisplay focuses only on displaying the image file
 * itself, while ImageGeneric is a fully-fledged component
 * with metadata (title...).
 *
 * TODO fuse with SimilarityApp.components.MatchGroup ?
 */

import React from "react";

import { ImageInfo } from "./types";
import { ImageIdentification, ImageFileDisplay } from ".";


export function ImageGeneric(props: { image: ImageInfo }) {
    const image = props.image;

    return (
        <div className="image-generic-outer-wrapper">
            <div className="image-generic-inner-wrapper">
                <div className="image-generic-title">
                    {<ImageIdentification image={image} filenameDisplay={false}/>}

                </div>
                <div className="image-generic-content mb-1">
                    <ImageFileDisplay image={image}></ImageFileDisplay>
                </div>
            </div>
        </div>
    )
}

// front/interface/src/shared/components/ImageGeneric.svelte
<script lang="ts">
    import type { TImageInfo } from "../types";
    import ImageFileDisplay from "./ImageFileDisplay.svelte";
    import ImageInfos from "./ImageInfos.svelte";

    interface Props {
        image: TImageInfo;
    }
    let { image }: Props = $props();
    let mounted = $state(false);

    $effect(() => {
        mounted = true;
    });
</script>

<div class="image-generic-outer-wrapper" style:opacity={mounted ? 1 : 0}>
    <div class="image-generic-inner-wrapper">
        <div class="image-generic-title">
            <ImageInfos {image} filenameDisplay={false} />
        </div>
        <div class="image-generic-content mb-1">
            <ImageFileDisplay {image} />
        </div>
    </div>
</div>

<style>
    .image-generic-outer-wrapper {
        transition: opacity 1s;
    }
</style>
