// front/webpack/src/shared/ImageGenericList.tsx
/**
 * an array of images displayed as a bulma `columns` inside an invisible `html:ul`
 */

import React from "react";

import { ImageGeneric } from ".";
import { ImageInfo } from "./types";


export function ImageGenericList(props: { imageArray:ImageInfo[] }) {
    const imageArray = props.imageArray;

    return (
        <ul className="columns is-mobile is-multiline list-invisible">
        { imageArray.map(image =>
            (<li key={image.id} className="column is-one-fourth is-flex">
                <ImageGeneric image={image}/>
            </li>)) }
        </ul>
    )
}

// front/interface/src/shared/components/ImageGenericList.svelte
<script lang="ts">
    import type { TImageInfo } from "../types";
    import ImageGeneric from "./ImageGeneric.svelte";

    /**
     * an array of images displayed as a bulma `columns` inside an invisible `html:ul`
     */

    interface Props {
        image_array: TImageInfo[];
    }
    let { image_array }: Props = $props();
</script>

<ul class="columns is-mobile is-multiline list-invisible">
    {#each image_array as image (image.id)}
        <li class="column is-one-fourth is-flex">
            <ImageGeneric {image}/>
        </li>
    {/each}
</ul>
